In [1]:
#decision tree classification

In [2]:
# import libraries

In [4]:
import pandas as pd
import numpy as np

In [5]:
data = pd.read_excel("C:/Users/91845/Downloads/Google ads hourly analysis 19th june.xlsx")

In [6]:
data

Sr_no  Impressions   Clicks  Cost      CTR        CPC  Cold Leads   \
0   00:00:00          5941     356    594  0.0600   1.666667           11   
1   00:30:00          4511     180    451  0.0400   2.500000            9   
2   01:00:00          3378     101    338  0.0300   3.333333            6   
3   01:30:00           652      26     65  0.0400   2.500000            1   
4   02:00:00           421       8     42  0.0200   5.000000            0   
5   02:30:00           110       2     11  0.0200   5.000000            0   
6   03:00:00            56       1      6  0.0200   5.000000            0   
7   03:30:00            42       1      4  0.0120   8.333333            0   
8   04:00:00             3       0      0  0.0110   9.090909            0   
9   04:30:00             8       0      1  0.0190   5.263158            0   
10  05:00:00            95       1     10  0.0140   7.142857            0   
11  05:30:00            64       1      6  0.0200   5.000000            0   
12  06:00:00            26       0      3  0.0020  50.000000            0   
13  06:30:00           193       4     19  0.0200   5.000000            0   
14  07:00:00           236       5     24  0.0220   4.545455            0   
15  07:30:00           463      23     46  0.0500   2.000000            1   
16  08:00:00           896      54     90  0.0600   1.666667            2   
17  08:30:00           486      34     49  0.0700   1.428571            1   
18  09:00:00           785      71     79  0.0900   1.111111            1   
19  09:30:00          1245     149    125  0.1200   0.833333            2   
20  10:00:00          1755     228    176  0.1300   0.769231            3   
21  10:30:00          1865     106    187  0.0569   1.757469            4   
22  11:00:00          2658     399    266  0.1500   0.666667            5   
23  11:30:00          3255     391    326  0.1200   0.833333            7   
24  12:00:00          3284     427    328  0.1300   0.769231            6   
25  12:30:00          4651     558    465  0.1200   0.833333            9   
26  13:00:00          4895     685    490  0.1400   0.714286           10   
27  13:30:00          4752     665    475  0.1400   0.714286            9   
28  14:00:00          4665     606    467  0.1300   0.769231            9   
29  14:30:00          4958     694    496  0.1400   0.714286           10   
30  15:00:00          5320     745    532  0.1400   0.714286           10   
31  15:30:00          5968     836    597  0.1400   0.714286           12   
32  16:00:00          5673     794    567  0.1400   0.714286           11   
33  16:30:00          4865    1216    487  0.2500   0.400000            9   
34  17:00:00          6593    1055    659  0.1600   0.625000           13   
35  17:30:00          8945    1700    895  0.1900   0.526316           18   
36  18:00:00          8444    1773    844  0.2100   0.476190           17   
37  18:30:00          8452    1944    845  0.2300   0.434783           17   
38  19:00:00          8757    2277    876  0.2600   0.384615           17   
39  19:30:00          8968    1883    897  0.2100   0.476190           18   
40  20:00:00          9425    1414    943  0.1500   0.666667           19   
41  20:30:00          9120    1277    912  0.1400   0.714286           18   
42  21:00:00          8945    1431    895  0.1600   0.625000           18   
43  21:30:00          7863    1179    786  0.1500   0.666667           16   
44  22:00:00          7521    1203    752  0.1600   0.625000           15   
45  22:30:00          9632    1830    963  0.1900   0.526316           19   
46  23:00:00         10230    1739   1023  0.1700   0.588235           20   
47  23:30:00          9452    1512    945  0.1600   0.625000           19   

    Warm Leads  Hot Leads  
0          5.0          2  
1          4.0          2  
2          3.0          1  
3          NaN          0  
4          0.0          0  
5          0.0          0  
6          0.0          0  
7        

In [7]:
a = data.drop("Sr_no", axis=1)

In [8]:
a.isnull().sum()

Impressions     0
Clicks          0
Cost            0
CTR             0
CPC             0
Cold Leads      0
Warm Leads      1
Hot Leads       0
dtype: int64

In [9]:
b = a.fillna(a.mean() )

In [10]:
b

Impressions   Clicks  Cost      CTR        CPC  Cold Leads   Warm Leads  \
0           5941     356    594  0.0600   1.666667           11    5.000000   
1           4511     180    451  0.0400   2.500000            9    4.000000   
2           3378     101    338  0.0300   3.333333            6    3.000000   
3            652      26     65  0.0400   2.500000            1    3.914894   
4            421       8     42  0.0200   5.000000            0    0.000000   
5            110       2     11  0.0200   5.000000            0    0.000000   
6             56       1      6  0.0200   5.000000            0    0.000000   
7             42       1      4  0.0120   8.333333            0    0.000000   
8              3       0      0  0.0110   9.090909            0    0.000000   
9              8       0      1  0.0190   5.263158            0    0.000000   
10            95       1     10  0.0140   7.142857            0    0.000000   
11            64       1      6  0.0200   5.000000            0    0.000000   
12            26       0      3  0.0020  50.000000            0    0.000000   
13           193       4     19  0.0200   5.000000            0    0.000000   
14           236       5     24  0.0220   4.545455            0    0.000000   
15           463      23     46  0.0500   2.000000            1    0.000000   
16           896      54     90  0.0600   1.666667            2    1.000000   
17           486      34     49  0.0700   1.428571            1    0.000000   
18           785      71     79  0.0900   1.111111            1    0.000000   
19          1245     149    125  0.1200   0.833333            2    1.000000   
20          1755     228    176  0.1300   0.769231            3    1.000000   
21          1865     106    187  0.0569   1.757469            4    2.000000   
22          2658     399    266  0.1500   0.666667            5    2.000000   
23          3255     391    326  0.1200   0.833333            7    3.000000   
24          3284     427    328  0.1300   0.769231            6    3.000000   
25          4651     558    465  0.1200   0.833333            9    4.000000   
26          4895     685    490  0.1400   0.714286           10    5.000000   
27          4752     665    475  0.1400   0.714286            9    4.000000   
28          4665     606    467  0.1300   0.769231            9    4.000000   
29          4958     694    496  0.1400   0.714286           10    5.000000   
30          5320     745    532  0.1400   0.714286           10    5.000000   
31          5968     836    597  0.1400   0.714286           12    6.000000   
32          5673     794    567  0.1400   0.714286           11    4.000000   
33          4865    1216    487  0.2500   0.400000            9    4.000000   
34          6593    1055    659  0.1600   0.625000           13    6.000000   
35          8945    1700    895  0.1900   0.526316           18    9.000000   
36          8444    1773    844  0.2100   0.476190           17    8.000000   
37          8452    1944    845  0.2300   0.434783           17    8.000000   
38          8757    2277    876  0.2600   0.384615           17    8.000000   
39          8968    1883    897  0.2100   0.476190           18    9.000000   
40          9425    1414    943  0.1500   0.666667           19    9.000000   
41          9120    1277    912  0.1400   0.714286           18    9.000000   
42          8945    1431    895  0.1600   0.625000           18    9.000000   
43          7863    1179    786  0.1500   0.666667           16    8.000000   
44          7521    1203    752  0.1600   0.625000           15    7.000000   
45          9632    1830    963  0.1900   0.526316           19    9.000000   
46         10230    1739   1023  0.1700   0.588235           20   10.000000   
47          9452    1512    945  0.1600   0.625000           19    9.000000   

    Hot Leads  
0           2  
1           2  
2           1  
3           0  
4           0  
5           0  
6           0  
7   

In [11]:
x = b.iloc[:,:-1].values

In [12]:
x

array([[5.94100000e+03, 3.56000000e+02, 5.94000000e+02, 6.00000000e-02,
        1.66666667e+00, 1.10000000e+01, 5.00000000e+00],
       [4.51100000e+03, 1.80000000e+02, 4.51000000e+02, 4.00000000e-02,
        2.50000000e+00, 9.00000000e+00, 4.00000000e+00],
       [3.37800000e+03, 1.01000000e+02, 3.38000000e+02, 3.00000000e-02,
        3.33333333e+00, 6.00000000e+00, 3.00000000e+00],
       [6.52000000e+02, 2.60000000e+01, 6.50000000e+01, 4.00000000e-02,
        2.50000000e+00, 1.00000000e+00, 3.91489362e+00],
       [4.21000000e+02, 8.00000000e+00, 4.20000000e+01, 2.00000000e-02,
        5.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.10000000e+02, 2.00000000e+00, 1.10000000e+01, 2.00000000e-02,
        5.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [5.60000000e+01, 1.00000000e+00, 6.00000000e+00, 2.00000000e-02,
        5.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [4.20000000e+01, 1.00000000e+00, 4.00000000e+00, 1.20000000e-02,
        8.33333333e+00, 0

In [13]:
y = b.iloc[:,-1].values

In [14]:
y

array([2, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 1, 2, 3, 3, 4, 3, 3, 4, 4, 4, 3,
       3, 4, 4, 4], dtype=int64)

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
x_train, x_test, y_train, y_test = train_test_split( x,y, test_size=0.20, random_state=50)

In [17]:
# Feature Scaling

In [18]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [19]:
x_train = sc.fit_transform(x_train)

In [20]:
x_test = sc.fit_transform(x_test)

In [21]:
#Training the Decision Tree Classification model on the Training set

In [22]:
from sklearn.tree import DecisionTreeClassifier

In [23]:
DT = DecisionTreeClassifier(criterion="gini",random_state=0)

In [24]:
DT.fit(x_train,y_train)

DecisionTreeClassifier(random_state=0)

In [25]:
print(DT.predict(sc.transform([[5942,356,594,0.0600,1.666667,11,5.0]])))

[2]


In [26]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [27]:
y_prediction = DT.predict(x_test)

In [28]:
y_prediction

array([3, 2, 3, 4, 0, 0, 0, 1, 0, 1], dtype=int64)

In [29]:
accuracy_score(y_test,y_prediction)

0.9